version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: XXXX
      MYSQL_USER: XXXX
      MYSQL_PASSWORD: XXXX
      MYSQL_INITDB_SKIP_TZINFO: 1
    ports:
      - '3307:3306'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=XXXX
      - DB_PASSWORD=XXXX
      - DB_NAME=XXXX
    depends_on:
      - db
    restart: always
