import { NgModule } from '@angular/core';
import { FeatherModule } from 'angular-feather';
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  BookOpen,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Edit3,
  Eye,
  EyeOff,
  FileText,
  Globe,
  Home,
  Inbox,
  Info,
  Layers,
  LogIn,
  LogOut,
  Mail,
  Menu,
  Monitor,
  Moon,
  Plus,
  Search,
  ShieldOff,
  Sun,
  Trash2,
  Users,
  X,
  Zap,
} from 'angular-feather/icons';

// Only the icons the templates actually use. angular-feather tree-shakes per
// icon, so an unused entry is dead weight — the previous list registered
// several no template referenced, while omitting the pagination chevrons, which
// therefore rendered as blank buttons.
const icons = {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  BookOpen,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Edit3,
  Eye,
  EyeOff,
  FileText,
  Globe,
  Home,
  Inbox,
  Info,
  Layers,
  LogIn,
  LogOut,
  Mail,
  Menu,
  Monitor,
  Moon,
  Plus,
  Search,
  ShieldOff,
  Sun,
  Trash2,
  Users,
  X,
  Zap,
};

@NgModule({
  imports: [FeatherModule.pick(icons)],
  exports: [FeatherModule],
})
export class IconModule {}
